### ISSUE TITLE
Support of foreign languages (FR, DE, ...)

### ISSUE THREAD

**Issue by mcapelle** [tomav/SublimeText2-Behat-Features-Syntax#1]
Hi,

I am interested in contributing to SublimeText2-Behat-Features by adding other languages keywords support.

To do that I fund 2 options :
- Duplicate _Behat-Features.JSON-tmLanguage_ and _Behat-Features.tmLanguage_ files to _Behat-Features-FR.tmLanguage_ (for example)
- Add all localized keywords in the _Behat-Features.JSON-tmLanguage_ and _Behat-Features.tmLanguage_ files that already exist

Drawback of the first solution is that the user gets N propositions of  features syntax for each languages support by the project. (While using the Control Panel)
Drawback of the second solution is that the _Behat-Features.JSON-tmLanguage_ and _Behat-Features.tmLanguage_ will contain all localized keywords and will be difficult to maintain.

Do you have an opinion on this before I send you a pull request ?

Regards.

**Comment by tomav** [comment]
Nice idea @mcapelle !
I'd probably split `Behat-Features.JSON-tmLanguage` file into 2 separates files : 
- `Behat-Features-Common.JSON-tmLanguage`
- `Behat-Features-{LANG}.JSON-tmLanguage` where `{LANG}` is FR / DE / ...

There is not a lot of data to translate in each language file :

``` javascript
    {
      "comment": "Behat definitions",
      "name": "keyword.control.source.behat",
      "match": "(Feature:|Examples:|Scenario:|Scenario Outline:|Background:)"
    },


    { 
      "comment": "Behat step keyword",
      "name": "keyword.operator.step.behat",
      "match": "(Given|When|And|But|Then)"
    },
```

And your idea could bring some other contributor to the project. Again, nice shot.

**Comment by mcapelle** [comment]
One more question :
In the `JSON-tmLanguage` and `tmLanguage` files there is an uuid value.
How is defined this value ? Can it be the same in all the `Behat-Features-{LANG}.JSON-tmLanguage` files ?

**Comment by tomav** [comment]
You just have to work on JSON files.
XML/PLIST format should be generated from JSON with AAAPackageDev : 
https://github.com/SublimeText/AAAPackageDev

It also will generate the automatic UUID.

I close this thread to focus on your lastest with PR.
